/* ========================================================================
 * Copyright 2014 grupo15
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo15

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_addressModel'], function() {
    App.Model.AddressModel = App.Model._AddressModel.extend({

 	validate: function(attrs,options){
            var validationMessage = "";
            
            if(!attrs.street){
                validationMessage += "The street must not be empty. ";
            }
            else{
                if(Number(attrs.street)===NaN)
                {
                    validationMessage += "The street must be a number. ";
                }
                else{
                    if(Number(attrs.street)>999)
                    {
                        validationMessage += "The street number can't have more than three digits";
                    }
                }
            }
            if(!attrs.aveneu){
                validationMessage += "The aveneu must not be empty. ";
            }
            else{
                if(Number(attrs.aveneu)===NaN)
                {
                    validationMessage += "The aveneu must be a number. ";
                }
                else{
                    if(Number(attrs.aveneu)>999)
                    {
                        validationMessage += "The aveneu number can't have more than three digits";
                    }
                }
                
            }
            if(attrs.cityId === "None")
            {
                validationMessage += "The city id must be specified";
            }
            
            
            
            if(validationMessage.length>0){
               return validationMessage;
            }
        }

    });

    App.Model.AddressList = App.Model._AddressList.extend({
        model: App.Model.AddressModel
    });

    return  App.Model.AddressModel;

});